version: '3'

services:

    nginx:
        build:
            dockerfile: ./docker/nginx.dockerfile
            context: .
        image: anderson/nginx
        container_name: nginx
        ports:
            - "80:80"
        networks: 
            - production-newtork
        depends_on: 
            - "node1"
            - "node2"
            - "node3"

    mongodb:
        image: mongo
        networks: 
            - production-newtork

    node1:
        build:
            dockerfile: ./docker/alura-books.dockerfile
            context: .
        image: anderson/alura-books
        container_name: alura-books-1
        ports:
            - "3000"
        networks: 
            - production-newtork
        depends_on: 
            - "mongodb"

    node2:
        build:
            dockerfile: ./docker/alura-books.dockerfile
            context: .
        image: anderson/alura-books
        container_name: alura-books-2
        ports:
            - "3000"
        networks: 
            - production-newtork    
        depends_on: 
            - "mongodb"
    
    node3:
        build:
            dockerfile: ./docker/alura-books.dockerfile
            context: .
        image: anderson/alura-books
        container_name: alura-books-3
        ports:
            - "3000"
        networks: 
            - production-newtork    
        depends_on: 
            - "mongodb"    

networks:
    production-newtork:
        driver: bridge